repos:
  - repo: https://github.com/ambv/black
    rev: "22.12.0"
    hooks:
    - id: black
      language_version: "3.11"
      args: ["--config=pyproject.toml"]
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
    - id: flake8
      language_version: "3.11"
      args: ["--config=.flake8"]
      additional_dependencies: ["flake8-bugbear"]
  - repo: https://github.com/pycqa/isort
    rev: "5.11.4"
    hooks:
      - id: isort
        language_version: "3.11"
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        language_version: "3.11"
        args: ["--config-file=pyproject.toml"]
